### ISSUE TITLE
请问我可以使用自己的数据集进行训练和预测吗？

### ISSUE THREAD

**Issue by 935462955** [RaleLee/Co-GAT#1]
我有一个仅包含对话行为标签而不包含情感标签的数据集，可以用来训练模型并预测吗？

**Comment by RaleLee** [comment]
你好！虽然我们这篇文章中做的是对话行为和情感联合预测模型，但是你可以修改代码，删除其中关于情感部分的模块，形成一个只对对话行为标签训练和预测的模型。
