### ISSUE TITLE
cuDNN version incompatibility

### ISSUE THREAD

**Issue by hemant5454** [RaleLee/Co-GAT#2]
Exception has occurred: RuntimeError
cuDNN version incompatibility: PyTorch was compiled  against (8, 5, 0) but found runtime version (8, 3, 3). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.

`File "/data/home/hemantmishra/Co-GAT/main.py", line 56, in <module>`
    `model = model.cuda()`
How to sole this?

**Comment by RaleLee** [comment]
Please try reinstalling pytorch with the right cuDNN version in your environment.
