### ISSUE TITLE
What you mean by train_adj.txt file in dataset section.

### ISSUE THREAD

**Issue by hemant5454** [RaleLee/Co-GAT#3]
What do you mean by train_adj.txt file in the dataset section? And How it will help in the Co-GAT model. Because the paper doesn't talk about this, right?

**Comment by RaleLee** [comment]
*_adj.txt is the _**Speaker-Level Encoder**_ graph edge table of the dataset. See _**Speaker-Level Encoder**_ subsection in paper. Please follow the paper to create them:

1.vertices: each utterance in the dialogue will be the vertex in the graph. Number the utterances in the order of the dialogue

2.edges: vertex i and vertex j should be connected if they belong to the same speaker. And we only consider the first-order neighbors to alleviate the overfitting problem. Don't forget the self-connected edge. Like a bi-speaker dialogue, 3 turns with 6 utterances. Utterance 1, 3 and 5 belong to the speaker1. Utterance 2, 4 and 6 belong to the speaker 2. Then the edges are 1-1, 2-2, 3-3, 4-4, 5-5, 6-6, 1-3, 3-5, 2-4, 4-6.
